spring.application.name=banking-api

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

admin.bootstrap.enabled=${ADMIN_BOOTSTRAP_ENABLED:true}
admin.bootstrap.national-id=${ADMIN_BOOTSTRAP_NATIONAL_ID:00000000000}
admin.bootstrap.email=${ADMIN_BOOTSTRAP_EMAIL:admin@evergreenbank.local}
admin.bootstrap.password=${ADMIN_BOOTSTRAP_PASSWORD:ChangeMe123!}
admin.bootstrap.first-name=${ADMIN_BOOTSTRAP_FIRST_NAME:Admin}
admin.bootstrap.last-name=${ADMIN_BOOTSTRAP_LAST_NAME:User}
admin.bootstrap.phone-number=${ADMIN_BOOTSTRAP_PHONE:05550000000}
admin.bootstrap.age=${ADMIN_BOOTSTRAP_AGE:30}