package com.ekim.bankingapi.notification;

public enum NotificationType {
    TRANSFER_SENT,
    TRANSFER_RECEIVED,
    DEPOSIT,
    WITHDRAWAL,
    LIMIT_EXCEEDED,
    ACCOUNT_LOCKED,
    INTEREST_CREDITED,
    SCHEDULED_TRANSFER_EXECUTED,
    SCHEDULED_TRANSFER_FAILED,
    CARD_ISSUED,
    CARD_BLOCKED,
    CARD_CANCELLED,
    CREDIT_CARD_CHARGED,
    CREDIT_CARD_PAYMENT_RECEIVED,
    CREDIT_STATEMENT_GENERATED,
    CREDIT_CARD_INTEREST_CHARGED,
    TWO_FACTOR_ENABLED,
    TWO_FACTOR_DISABLED
}
